### ISSUE TITLE
Helper on port 3 is failing

### ISSUE THREAD

**Issue by ahrorkosimi** [doug-leith/appFirewall#1]
After installing (by dragging app to Applications' folder) and starting the app, appFirewall asks for administrator's password. I enter it, it launches but then after 5 seconds, it shows error (screenshot below). I restart the app, it happens again (loop). I disabled MacOS firewall and checked my other settings, nothing should interfere with the app. 

Using MacOS Catalina 10.15.2.  

<img width="532" alt="Screen Shot 2019-12-26 at 10 28 55 PM" src="https://user-images.githubusercontent.com/29758568/71485821-e8f4f700-2834-11ea-8191-d995863c81c9.png">

**Comment by doug-leith** [comment]
thanks for the feedback.  could you send me the following two log files to help me try to figure out what the source of the problem is:  /Library/Logs/appFirewall-Helper.log and ~/Library/Application\ Support/appFirewall/app_log.txt.  

doug

**Comment by ahrorkosimi** [comment]
Dear Doug. Thank you for taking time to look at the issue. Here are requested files.  Please let me know if you need any other file. Would love to get this app working on my mac. 

[app_log.txt](https://github.com/doug-leith/appFirewall/files/4005603/app_log.txt)
[appFirewall-Helper.log](https://github.com/doug-leith/appFirewall/files/4005604/appFirewall-Helper.log)

**Comment by doug-leith** [comment]
I have it.  Your traffic is being routed via device ppp0 and so isn't an ethernet link layer.  Easy enough to fix up, I'll post an update and let you know.  In the meantime, if you'd like to test things then using an ethernet interface as the default route should make things run ok.

**Comment by doug-leith** [comment]
By the way, if your device ppp0 is an encrypted tunnel (which I guess it is) then application packets are encapsulated inside the tunnel packets.  That means the final destination address of the application packets is not visible to the firewall (only the other end of the tunnel can be identified from the IP header of the tunnel packets, everything else is encrypted).  In that case the firewall is hamstrung, although it might still be able to do some limited filtering - I'm looking into that just now.

**Comment by ahrorkosimi** [comment]
Hi Doug. I use PPTP vpn from time to time but helper was giving error even when i turned of VPN via my wifi home network. If you compile new .dmg, please let me know. I will reinstall and check for bugs.

**Comment by doug-leith** [comment]
I just posted an updated here:

https://github.com/doug-leith/appFirewall/raw/master/latest%20release/appFirewall.dmg

Would you mind giving it a try and let me know how you get on, thanks.

Doug

**Comment by ahrorkosimi** [comment]
Thank you for fixing. I have been testing for couple weeks now and it seems to be working as intended. While I find blacklisting/whitelisting domains quite easy is there any way i could drag and drop application to block all connection from that app? I have looked everywhere in the app, couldn't find it.

**Comment by doug-leith** [comment]
Good idea, let me have a think about how to provide a clean UI for that (the functionality is already there and can be configured via the host list files, its just a UI matter).  As a temporary workaround, take a look at the file dougs_blocklist.txt in ~/Library/Application\ Support/appFirewall/.  You can edit that as you like and then reload via the firewall preferences.  The format for entries is as follows:

# The format of each line is:
# <app name>, [-]<domain>
# where <app name> is 16 character name reported by ps, or can be wildcard * e.g:
# *,<domain>
# in which case domain is blocked for all apps.
# A - preceding a domain name adds it to the whitelist.  The domain wildcard * is allowed # e.g. the line:
# Dropbox,*
# blocks all domains for app Dropbox, and the line:
# Dropbox,-client.dropbox.com
# adds client.dropbox.com to the whitelist for Dropbox, so the net effect is that all
# domains apart from client.dropbox.com are blocked.

**Comment by doug-leith** [comment]
Turned out to be super easy to add block/allow of all connections, I just posted a new release for you to play with ;-)  Right click on a connection to get the option to block/allow everything for that app.  IPv6 handling is much better in this version too.

**Comment by ahrorkosimi** [comment]
Thank you so much for adding additional features! I wanted to update the app through menu, but for some reason giving this error. Screenshot attached. 

<img width="580" alt="Screen Shot 2020-01-13 at 6 41 13 PM" src="https://user-images.githubusercontent.com/29758568/72260331-7194d500-3634-11ea-8bd9-74e2844089a7.png">

Downloading new .dmg to test. Also an app icon in menu bar would be easy than having it on the dock. I don't know to what extend it is difficult to implement, but thank you for your updates.

**Comment by doug-leith** [comment]
that's a strange one.  what folder were you running the app in when you tried to update it ?  re the menu bar, there is an app icon there already ...

**Comment by ahrorkosimi** [comment]
It's in Applications folder just like other apps. Installed the update via .dmg from github. Regarding the app icon in the menu, i have checked Preferences there are 3 options (1.check for updates monthly; 2.automatically install updates; 3.run at login). Nothing about menu icon.

**Comment by ahrorkosimi** [comment]
Feedback: also, when Application has "allow all connection from this app" and user adds the same application to blacklist with "block all connection from this app", whitelist will prevail and there is no warning to user that the app in question is already in the whitelist.

**Comment by doug-leith** [comment]
its always there, i didn't add an option to enable/disable it.  it looks like the dock item, only smaller -- see towards the middle of this screenshot:

<img width="1086" alt="Screenshot 2020-01-13 at 15 54 20" src="https://user-images.githubusercontent.com/2244142/72270490-23c0a280-361d-11ea-9fa4-158fc385fdbb.png">

the dock icon should disappear when the firewall window is closed, and can be reopened by clicking on the menubar icon.

re the updating problem, could you send me the ~/Library/Application\ Support/appFirewall/app_lot.txt file please and I'll see if I can diagnose what went wrong.

**Comment by doug-leith** [comment]
re the whitelist/blacklist business, thanks i'll look into adding a warning.

**Comment by ahrorkosimi** [comment]
app_log.txt is attached. 

[app_log.txt](https://github.com/doug-leith/appFirewall/files/4054479/app_log.txt)

I wonder why icon on menu bar is not showing. Is it because I use standard user, perhaps? For safeguarding reasons, I install apps via admin but run all my apps in standard user. If there is any log i can share to find out why it is not showing the icon, please let me know.

**Comment by ahrorkosimi** [comment]
After reboot, the app window opens, when i close there is no way to bring it back. If I open the app again, it doesn't do anything. The dock icon disappeared from dock. I have to quit the app from activities app then relaunch it. I am supposing it started from version 1.9.

**Comment by doug-leith** [comment]
Here's the actual error when you tried to update: "Problem when trying to install update, couldn't copy updated app into final location: You don’t have permission to save the file “appFirewall.app” in the folder “Applications”.   So it looks like when you run with reduced permissions you can't auto update the app (for what its worth, I just run as an ordinary user and copy it to my ~/Applications folder and run from there).  So I think that's one issue sorted ;-)  Now for the rest ...

(thanks for your patience with all this btw, its super helpful to me)

**Comment by doug-leith** [comment]
re the behaviour after reboot, my current guess is that there is some (perhaps permissions, perhaps not) problem with creating the menubar item.  the fact that the dock icon disappears is "correct" behaviour, since its supposed to be replaced by the menubar icon.  

could you send me the more recent ~/Library/Application\ Support/appFirewall/app_log.txt file from the time when you rebooted, perhaps there is a hint in that.   regardless, i'll also add a check for whether creation of the menubar item succeeded before disappearing the dock icon, as that seems like a nasty catch 22 alright.

**Comment by doug-leith** [comment]
just to be clear on installing the app, you don't need to be root to do that.  its ok to just copy the app to your Applications folder as an ordinary user.   when first run the app asks for a root password to install its helper, but that's the only time elevated permissions are needed during install.

**Comment by doug-leith** [comment]
I posted a new release (v1.9.1) that should dump some extra diagnostic info about the menubar into app_log.txt, would you mind giving it a try and sending me the log file, thanks !

**Comment by ahrorkosimi** [comment]
Hi Doug, here is app_log file that I hope will be helpful. The app is running in the background, but there is now way to bring it forward as it is missing menubar icon. I have to force close the app and reopen it to manage my connections for now. I have rebooted and reopened the app so it can log in the file and you can take a further look. 

[app_log.txt](https://github.com/doug-leith/appFirewall/files/4064209/app_log.txt)

I wonder why I can't update via update menu just like other apps. Other apps update just fine under my standard user. Also, when my macbook reboots, appFirewall window pops out which is fine because it is set to auto-start at login, however, i don't see the app in the Preference>Users>Login items like my other apps. Perhaps the issue is somehow related to this? Just speculating. 

My pleasure to be part of this and your efforts to make it a great mac firewall app.

**Comment by doug-leith** [comment]
> _Hi Doug, here is app_log file that I hope will be helpful. The app is running in the background, but there is now way to bring it forward as it is missing menubar icon. I have to force close the app and reopen it to manage my connections for now. I have rebooted and reopened the app so it can log in the file and you can take a further look.
> 
> app_log.txt
> 
Thanks.  Is that log for v1.9.1 ?  If so, the log says there’s been no problem with creating the_ menubar icon  - so the setup is failing completely silently !  I instrumented every statement required to setup the menubar sop if any failed I shoul;d have seen an message in the log.   So its a bit of a mystery.  I’ll give it some more thought.

> I wonder why I can't update via update menu just like other apps.

That I think I understand.  If i have it right you installed the app by logging in as root and copying the app over to Applications, then logging out and back in as a regular user — do i have that right ?  

If so, i suspect you end up with the app files being owned by root even though it can be executed by anyone.  When you then execute it as an ordinary user the app doesn’t have permission to update its files (since they’re owned by root) - that’s what the error I see in the log says.  One solution is to delete the app from the Applications folder (I guess you’ll need to be root to do that), then when logged in as your usual ordinary user copy the app over to the Applications folder, that should (hopefully!) fix the permissions issue since you’ll be running the app as the same user that installed it.  Might even fix the mystery menubar problem too, but that’s pure speculation.

> Other apps update just fine under my standard user. Also, when my macbook reboots, appFirewall window pops out which is fine because it is set to auto-start at login, however, i don't see the app in the Preference>Users>Login items like my other apps. Perhaps the issue is somehow related to this? Just speculating.
Its new apple technology ;-)  They changed the way apps startup at login, use of Preferences is the legacy approach, now deprecated.  The new approach is by one of two ways: (i) like you did it, ask to reopen apps on restart (eiher in answer to the popup on rebooting or by right clicking the app on the dock), (ii) do it via the app itself - if you look in the appFirewall preferences there’s an option to enable/disable startup on login (which is disabled by default).

> My pleasure to be part of this and your efforts to make it a great mac firewall app.
Thanks !

Doug

**Comment by ahrorkosimi** [comment]
Yes, the app version I have been using is 1.9.1  

My mac setup is that I have admin account with highest privileges for installing and maintaining security of all users. Then I have standard user for all my daily activities and apps. Whenever I want to install an app to /Applications folder under my standard user or make system wide changes, the app (or system preferences for example) asks to enter admin's login credentials, I enter it once, it will work for good.  I don't log out of the current user to install or make changes, only enter admin's credentials pop out window while i am using standard user. 

I hope that helps.

**Comment by doug-leith** [comment]
Yes, v helpful - I had misunderstood, sorry.   Could you send me the output of these commands please:

ls -alh /Applications/appFirewall.app

mdfind "kMDItemCFBundleIdentifier == com.leith.appFirewall"

(the first one will show the permissions on the app folder, the second shows where all executables with the identifier com.leith.appFirewall are located, just being super careful to confirm its really just in /Applications/appFirewall.app and there's no copy been left someplace else).

Thanks.

**Comment by ahrorkosimi** [comment]
Below is the results: 
________
ahror@aimtostar-MacBook-Pro ~ % ls -alh /Applications/appFirewall.app
total 0
drwxr-xr-x@  3 ahror  admin    96B Jan 14 00:43 .
drwxrwxr-x+ 37 root   admin   1.2K Jan 14 10:45 ..
drwxr-xr-x@ 10 ahror  admin   320B Jan 14 00:43 Contents
________
ahror@aimtostar-MacBook-Pro ~ % mdfind "kMDItemCFBundleIdentifier == com.leith.appFirewall"
/Applications/appFirewall.app
ahror@aimtostar-MacBook-Pro ~ %

**Comment by doug-leith** [comment]
thanks.  would you mind trying release v1.9.3 that i just posted.  it doesn't fix the menubar issue, but should fall back to leaving the dock icon showing and so the app should go back to being usable again.   would you also mind trying to do an update with the new app - this will likely fail with a permissions error again but I've added more logging, so if you could send me app_log.txt after trying to do the update that would be great.  thanks again.

doug

**Comment by ahrorkosimi** [comment]
Did complete uninstall and installed fresh from latest release v1.9.3 dmg. Installed as i usually install my other apps, upon first launch it asked to install application helper. I entered my admin login information, appFirewall opens fine. Closing application still does not show menu icon but dock icon is still there from where I can open and continue monitoring the app. Since v.1.9.3 is the latest release, appFirewall did not find any new version to update. Once you release newer version, I will retry it. 

Below is the app log. 
[app_log.txt](https://github.com/doug-leith/appFirewall/files/4070924/app_log.txt)

**Comment by doug-leith** [comment]
phew, glad the dock icon is back.  could you send me the log file since it should have extra info about the menubar button in it even without doing an update.  thanks

**Comment by doug-leith** [comment]
i think i might have figured out why the menu bar button doesn't appear.   from your screen shots it looks like your colour scheme is dark-mode or the like, is that right ?  when i turn on dark mode on my laptop the menubar goes dark (of course) and that makes the button disappear since its also dark !  i'll change the icon used to be lighter when in dark mode.

**Comment by doug-leith** [comment]
would you mind trying v1.9.4 that I just pushed -- works fine in dark mode on my machine (whereas before the menubar button was invisible since it was the same colour as the menubar).  hopefully that just leaves the updating permissions error to resolve (perhaps you send me the app_log.txt file if you see this error when updating to v1.9.4, thanks).

**Comment by ahrorkosimi** [comment]
Wow. Amazing how simple dark mode turned the menu icon into puzzle. I actually tested with v1.9.3 and i hovered my mouse and did blind click on end of menu bar and voila menu icon appeared as i clicked the end of menu bar. Thank you so much for figuring this out. Now we can hide the dock icon upon close as it is showing correct color. 

I also did update via app menu and still permission issue persists. Below is screenshot. 
<img width="580" alt="Screen Shot 2020-01-17 at 7 35 24 AM" src="https://user-images.githubusercontent.com/29758568/72580405-c74fd280-38fd-11ea-85b2-ea75fe75161d.png">

**Comment by doug-leith** [comment]
That's great.  Could you send me the app_log.txt file please - I added some extra logging to the code that does the updating and so the log file might contain a clue to what's going on with that.  Thanks.

**Comment by ahrorkosimi** [comment]
Here is the log file. 

[app_log.txt](https://github.com/doug-leith/appFirewall/files/4076786/app_log.txt)

Also, as I have been using the app and thinking of improvements, here is the wishlist/issues that might be helpful in future iterations of the app:
	•	Update via menu app (root permission issue)
	•	No appearance in System Preferences>Users>Login Items
	•	Notification on blacklisting/whitelisting app at the same time
	•	Blacklisting/whitelisting app before launching (maybe add application menu?)
	•	Show/hide dock icon (select from app preferences)
	•	Add ability to add domain (like google.com or Facebook.com) to blacklist/whitelist

**Comment by doug-leith** [comment]
> •	Update via menu app (root permission issue)
You mean the current issue ?  Agreed that needs fixed, am working on it ;-)

> •	No appearance in System Preferences>Users>Login Items
Ok, its easy to do I just didn’t include that since its deprecated by apple.

> •	Notification on blacklisting/whitelisting app at the same time
Done. Iif there’s a clash then in the black list pane the problematic rule will be highlighted in red.

> •	Blacklisting/whitelisting app before launching (maybe add application menu?)
I don’t quite follow, what do you have in mind exactly ?

> •	Show/hide dock icon (select from app preferences)
Yes, good idea.  Defaulting to the menubar wasn’t a great idea.

> •	Add ability to add domain (like google.com or Facebook.com) to blacklist/whitelist
that’s already possible via the hostname files, but not via the UI just now - the main issue I think is how to keep the UI clean and simple, the more options and ways to add rules the more scope for messups that might just confuse people (the whitelist/blacklist thing being one example).  maybe the solution is to allow people to load personalised hostname files (where they can edit the rules as they like, attractive to power users only I suspect) ?

**Comment by doug-leith** [comment]
Would you mind trying v1.9.5 that I just pushed, thanks.  Hopefully fixes the update problem (I played a small trick so you can test the updating without waiting for another release).    Would you mind also sending me app_log.txt after trying an update, thanks.

This version also has most of the features requested (block domains by right-clicking, optional menubar button via prefs) plus an extra option to block QUIC connections.  As for adding a Login Items entry, this seems to be deprecated by apple since MAC OS 10.11 - the preferred apple way is as is done in the firewall just now.

**Comment by ahrorkosimi** [comment]
Checked with version 1.9.5 (1). Screenshot below. 

<img width="396" alt="Screen Shot 2020-01-19 at 3 49 47 PM" src="https://user-images.githubusercontent.com/29758568/72683076-ff216a80-3af5-11ea-909d-def60965769b.png">

Here is the attempt to update via app menu. 

<img width="580" alt="Screen Shot 2020-01-19 at 3 49 38 PM" src="https://user-images.githubusercontent.com/29758568/72683080-09dbff80-3af6-11ea-9335-e049df4bc09b.png">

**Comment by ahrorkosimi** [comment]
Here is the log file. 
[app_log.txt.zip](https://github.com/doug-leith/appFirewall/files/4082804/app_log.txt.zip)

**Comment by ahrorkosimi** [comment]
Didn't quite get what's the QUIC connections for. Would love to read further if you have reference or link to share.

**Comment by doug-leith** [comment]
hmm, interesting.  could you also send me the log file /Library/Logs/appFirewall-Helper.log, thanks.

doug

**Comment by ahrorkosimi** [comment]
Here you go. 
[appFirewall-Helper.log](https://github.com/doug-leith/appFirewall/files/4082953/appFirewall-Helper.log)

**Comment by doug-leith** [comment]
thanks.  it looks like you did an update once and it worked fine, then tried a second time and it failed.  do i have that right ?

doug

**Comment by doug-leith** [comment]
if i have that right, then i think i know what happened (i didn't fully push the latest update to github, so when v1.9.5 updates itself it got into a messed up state).  would you mind doing a clean install of v1.9.5 (download from github and copy to /Applications).  after that updates should work fine (fingers crossed !)

**Comment by ahrorkosimi** [comment]
Indeed you are right. First time it seemed like it updated cause appFirewall restarted, but upon checking and attempting to update again, it gives error. I have completely removed the app, reinstalled from fresh 1.9.5 version, did update check, it downloaded, mounted dmg and restarted the app as normal. Upon second attempt, it gives error. I understand why it might do it. 

New logs are below, just in case. 
[app_log.txt](https://github.com/doug-leith/appFirewall/files/4084031/app_log.txt)

**Comment by ahrorkosimi** [comment]
[appFirewall-Helper.log](https://github.com/doug-leith/appFirewall/files/4084033/appFirewall-Helper.log)

**Comment by doug-leith** [comment]
thanks.  those logs say the update worked fine ?

**Comment by doug-leith** [comment]
thanks a lot for your help with testing and suggestions for features etc, and patience with the various glitches.  if you can spare the time, would you mind taking a look at version 1.9.6 that I've just pushed.   it includes support for dragging and dropping apps (and copying and pasting) onto the blacklist and whitelist, as well as manual entry of new rules.  i also added an embedded dns-over-https server (dnscrypt-proxy, one of the standard ones) so that DNS traffic can be encrypted.  i'm hoping this is close to the final release version (perhaps the triumph of hope over experience !).
